Traceback (most recent call last):
  File "/Users/indiram/Work/CAC/rss_reader/feedreader.py", line 7, in <module>
    from supabase import Client
  File "/Users/indiram/Library/Python/3.9/lib/python/site-packages/supabase/__init__.py", line 6, in <module>
    from .client import Client, create_client
  File "/Users/indiram/Library/Python/3.9/lib/python/site-packages/supabase/client.py", line 10, in <module>
    from .lib.auth_client import SupabaseAuthClient
  File "/Users/indiram/Library/Python/3.9/lib/python/site-packages/supabase/lib/__init__.py", line 1, in <module>
    from supabase.lib import auth_client, realtime_client
  File "/Users/indiram/Library/Python/3.9/lib/python/site-packages/supabase/lib/auth_client.py", line 3, in <module>
    from gotrue import SyncGoTrueClient, SyncMemoryStorage, SyncSupportedStorage
ImportError: cannot import name 'SyncGoTrueClient' from 'gotrue' (/Users/indiram/Library/Python/3.9/lib/python/site-packages/gotrue/__init__.py)Traceback (most recent call last):
  File "/Users/indiram/Work/CAC/rss_reader/feedreader.py", line 75, in <module>
    with open ('rss_feeds.csv') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'rss_feeds.csv'
Articles Added
